import turtle

screen = turtle.Screen()
screen.screensize(canvwidth=500, canvheight=500)
screen.bgcolor("cornflowerblue")
t=turtle.Turtle()
t.speed(0)


#grass
t.penup()
t.goto(-5000,-50)
t.pendown()
t.fillcolor("forestgreen")
t.pencolor("forestgreen")
t.begin_fill()
t.goto(5000,35)
t.goto(5000,-5000)
t.goto(-5000,-5000)
t.goto(-5000,35)
t.end_fill()

#tree1
t.penup()
t.goto(170,-100)
t.pendown()
t.pencolor("brown")
t.pensize(20)
t.goto(170,50)
t.pencolor("green")
t.fillcolor("green")
t.begin_fill()
t.circle(43)
t.end_fill()
t.penup()
t.goto(190,40)
t.pendown()
t.begin_fill()
t.circle(43)
t.end_fill()
t.penup()
t.goto(160,40)
t.pendown()
t.begin_fill()
t.circle(53)
t.end_fill()
t.goto(130,40)
t.pendown()
t.begin_fill()
t.circle(53)
t.end_fill()
t.goto(220,40)
t.pendown()
t.begin_fill()
t.circle(53)
t.end_fill()
t.goto(145,80)
t.pendown()
t.begin_fill()
t.circle(48)
t.end_fill()
t.goto(215,70)
t.pendown()
t.begin_fill()
t.circle(53)
t.end_fill()

#tree2
t.penup()
t.goto(-170,-100)
t.pendown()
t.pencolor("brown")
t.pensize(20)
t.goto(-170,50)
t.pencolor("green")
t.fillcolor("green")
t.begin_fill()
t.circle(43)
t.end_fill()
t.penup()
t.goto(-190,40)
t.pendown()
t.begin_fill()
t.circle(43)
t.end_fill()
t.penup()
t.goto(-160,40)
t.pendown()
t.begin_fill()
t.circle(53)
t.end_fill()
t.goto(-130,40)
t.pendown()
t.begin_fill()
t.circle(53)
t.end_fill()
t.goto(-220,40)
t.pendown()
t.begin_fill()
t.circle(53)
t.end_fill()
t.goto(-145,80)
t.pendown()
t.begin_fill()
t.circle(48)
t.end_fill()
t.goto(-215,70)
t.pendown()
t.begin_fill()
t.circle(53)
t.end_fill()

#sun
t.penup()
t.goto(250,300)
t.pendown()
t.pencolor("yellow")
t.fillcolor("yellow")
t.begin_fill()
t.circle(85)
t.end_fill()

#bench
t.penup()
t.goto(50,-200)
t.pendown()
t.pencolor("brown")
t.fillcolor("brown")
t.pensize(1)
t.begin_fill()
t.goto(155,-200)
t.goto(155,-240)
t.setheading(180)
t.goto(130,-240)
t.goto(130,-220)
t.goto(75,-220)
t.goto(75,-240)
t.goto(50,-240)
t.goto(50,-200)
t.end_fill()

#cLOUDs
t.penup()
t.goto(-250,375)
t.pendown()
t.pencolor("white")
t.fillcolor("white")
t.begin_fill()
t.circle(45)
t.penup()
t.goto(-220,330)
t.pendown()
t.circle(40)
t.penup()
t.goto(-180,300)
t.pendown()
t.circle(40)
t.penup()
t.goto(-160,350)
t.pendown()
t.circle(38)
t.penup()
t.goto(-250,300)
t.pendown()
t.circle(45)
t.penup()
t.goto(-145,290)
t.pendown()
t.circle(40)
t.end_fill()

#picnic blanket
t.pencolor("black")
size_x = 25
size_y = 25
for x in range(7):
    for j in range(5):
        t.penup()
        t.goto(-200+x*size_x, -200-j*size_y)
        t.pendown()
        if j %2 ==0:
            if x%2 ==0:
                t.fillcolor('red')
            else:
                t.fillcolor('white')
        else:

            if x % 2 == 1:
                t.fillcolor('red')
            else:
                t.fillcolor('white')

        t.begin_fill()
        for i in range(4):
            t.forward(size_x)
            t.left(90)
        t.end_fill()


#kite
t.penup()
t.goto(10,130)
t.pendown()
t.setheading(45)
t.fillcolor("yellow")
t.begin_fill()
for s in range(4):
    t.forward(45)
    t.left(90)
t.end_fill()
t.setheading(270)
t.pencolor("black")
t.pensize(3)
t.forward(30)
t.circle(30,60)
t.penup()
t.pencolor("white")
t.goto(10,130)
t.pendown()
t.goto(10,190)
t.penup()
t.goto(-15,160)
t.pendown()
t.goto(45,160)

#ball
t.penup()
t.goto(215,-220)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.circle(35)
t.end_fill()
t.pencolor("black")
t.begin_fill()
t.fillcolor("black")
t.penup()
t.goto(230,-180)
t.pendown()
t.setheading(225)
t.forward(10)
t.setheading(270)
t.forward(15)
t.left(90)
t.forward(20)
t.left(90)
t.forward(15)
t.setheading(135)
t.goto(230,-180)
t.end_fill()

#pond
t.penup()
t.goto(-80,-55)
t.pendown()
t.pencolor("blue")
t.fillcolor("blue")
t.begin_fill()
t.setheading(180)
t.circle(35,180)
t.setheading(0)
t.forward(150)
t.setheading(360)
t.circle(35,180)
t.forward(150)
t.end_fill()

#text
t.penup()
t.goto(45,250)
t.pendown()
t.pencolor("forestgreen")
t.write("Welcome, Spring!", font=("Arial", 22, "bold"), align="center")


turtle.done()